#!/usr/bin/ash

run_latehook() {

  local sysadmin_state_subvol="@sysadmin_state"      ########## change here and all scritps in /usr/local/sbin

	local root_mnt="/new_root"
	
	local lower_dir_etc="/new_root/etc"
	
	local lower_dir_home="/new_root/home"

	local lower_dir_systemd="/new_root/usr/lib/systemd"

	local lower_dir_var="/new_root/var"

	local lower_dir_vartmp="/new_root/var/tmp"
	
	local lower_dir_roothome="/new_root/root"

	local lower_dir_usrlocal="/new_root/usr/local"
	
	local lower_dir_mnt="/new_root/mnt"

	local lower_dir_opt="/new_root/opt"

	local lower_dir_srv="/new_root/srv"

    local real_block_device=$(resolve_device "$root");

	local root_overlay_protect=$(mktemp -d -p /)	


    btrfs property set -ts ${root_mnt} ro true  && ### set read-only in stateless-arch transactional


	local sysadmin_overlay=$(mktemp -d -p /)	


	mount "${real_block_device}" -t btrfs -o "compress-force="zstd,subvol=${sysadmin_state_subvol} ${sysadmin_overlay} &&
	mkdir -p ${sysadmin_overlay}/etc -v &&
	mkdir -p ${sysadmin_overlay}/home -v &&
	mkdir -p ${sysadmin_overlay}/systemd -v &&
	mkdir -p ${sysadmin_overlay}/var -v &&
	mkdir -p ${sysadmin_overlay}/roothome -v &&
	mkdir -p ${sysadmin_overlay}/usrlocal -v &&
	mkdir -p ${sysadmin_overlay}/mnt -v &&
	mkdir -p ${sysadmin_overlay}/opt -v &&
	mkdir -p ${sysadmin_overlay}/srv -v &&
	mkdir -p ${sysadmin_overlay}/work_etc -v &&
	mkdir -p ${sysadmin_overlay}/work_home -v &&
	mkdir -p ${sysadmin_overlay}/work_systemd -v &&
	mkdir -p ${sysadmin_overlay}/work_var -v &&
	mkdir -p ${sysadmin_overlay}/work_roothome -v &&
	mkdir -p ${sysadmin_overlay}/work_usrlocal -v &&
	mkdir -p ${sysadmin_overlay}/work_mnt -v &&
	mkdir -p ${sysadmin_overlay}/work_opt -v &&
	mkdir -p ${sysadmin_overlay}/work_srv -v &&


	mount -t overlay overlay -o lowerdir=${lower_dir_etc},upperdir=${sysadmin_overlay}/etc,workdir=${sysadmin_overlay}/work_etc,index=off,metacopy=off ${root_mnt}/etc &&	
	mount -t overlay overlay -o lowerdir=${lower_dir_systemd},upperdir=${sysadmin_overlay}/systemd,workdir=${sysadmin_overlay}/work_systemd,index=off,metacopy=off ${root_mnt}/usr/lib/systemd &&	
	mount -t overlay overlay -o lowerdir=${lower_dir_var},upperdir=${sysadmin_overlay}/var,workdir=${sysadmin_overlay}/work_var,index=off,metacopy=off  ${root_mnt}/var &&
	mount -t overlay overlay -o lowerdir=${lower_dir_roothome},upperdir=${sysadmin_overlay}/roothome,workdir=${sysadmin_overlay}/work_roothome,index=off,metacopy=off  ${root_mnt}/root &&
	mount -t overlay overlay -o lowerdir=${lower_dir_usrlocal},upperdir=${sysadmin_overlay}/usrlocal,workdir=${sysadmin_overlay}/work_usrlocal,index=off,metacopy=off  ${root_mnt}/usr/local &&
	mount -t overlay overlay -o lowerdir=${lower_dir_mnt},upperdir=${sysadmin_overlay}/mnt,workdir=${sysadmin_overlay}/work_mnt,index=off,metacopy=off  ${root_mnt}/mnt &&
	mount -t overlay overlay -o lowerdir=${lower_dir_opt},upperdir=${sysadmin_overlay}/opt,workdir=${sysadmin_overlay}/work_opt,index=off,metacopy=off  ${root_mnt}/opt &&
	mount -t overlay overlay -o lowerdir=${lower_dir_srv},upperdir=${sysadmin_overlay}/srv,workdir=${sysadmin_overlay}/work_srv,index=off,metacopy=off  ${root_mnt}/srv && ####################### remove && to disable home overlay
    mount -t overlay overlay -o lowerdir=${lower_dir_home},upperdir=${sysadmin_overlay}/home,workdir=${sysadmin_overlay}/work_home,index=off,metacopy=off  ${root_mnt}/home ####################### comment to disable home overlay 
}
